### ISSUE TITLE
READMEs and Documentation

### ISSUE THREAD

**Issue by jhauswald** [clarityinc/clarityeco#23]
After everyone's PRs get merged for demo-0.1, I'd like to make sure we don't forget about the documentation. The READMEs are pretty weak and the documentation is non-existent. We need to standardize the formats, there are multiple READMEs per service and I think they should be unified, they're a little confusing to navigate.

README is something you look at to get the service running. Format for the README:
- 1 line what it does with the input and output
- Detailed list of dependencies
- Steps to compile
- Steps to run

The documentation is something you look at to better understand what is happening in the service, details about algorithms/techniques, how it can relate to larger systems, and what exactly is modifiable. Format for the Documentation:
- What it does
- Objective of the service
- How it accomplishes that objective + links to resources
- Modifiable pieces
- If its in a workflow, what's its role

What do you guys think @twurman @Thomas-Yang @llotneb @cdmeister ?

**Comment by twurman** [comment]
Where would the documentation go? I think a github marked down outline for both of these would be good to see

**Comment by jhauswald** [comment]
Yea this would be markdown.

**Comment by cdmeister** [comment]
Do you want one README in the top of each service directory that describes how to run both sirius and template versions?

**Comment by twurman** [comment]
Thats what I did for IMM. It makes it easier if you only have to read one
thing.

On Wed, Jul 1, 2015 at 10:42 PM, cdmeister <notifications@github.com> wrote:

> Do you want one README in the top of each service directory that describes
> how to run both sirius and template versions?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clarityinc/clarityeco/issues/23#issuecomment-117880526>
> .
>



-- 
Timothy R. Wurman
University of Michigan
BSE Computer Science
twurman@umich.edu | 978-760-2208

**Comment by jhauswald** [comment]
Yea exactly I found myself looking for readmes I wasn't sure where to look. One unified readme is fine. And it's not like they're going to be super long anyways

**Comment by jhauswald** [comment]
readmes are being loved and taken care of, no need for an issue anymore
