### ISSUE TITLE
Tiantong's plan

### ISSUE THREAD

**Issue by VivienZhou** [clarityinc/clarityeco#44]
##### 7.21-7.24
- [x] Delete ```./templates``` and modify relevant files
- [x] Write wiki for NLP service
- [x] Setup opencv and OCR

##### 7.27-7.31
- [x] Read original files for OCR
- [x]  Learn cv::text::OCRTesseract Class Reference

##### 8.3-8.7
- [x] Try and compare different methods to preprocess images 
- [x]  Using Matlab to detect the text area
- [x] Utilize and test ocropy, an open-source OCR application using DNN

##### 8.10-8.15
- [ ] Notes on OCR
- [ ]  Report

**Comment by jhauswald** [comment]
Can you make this into checkboxes, tough to see where you are... like:
- [ ] today I made a checkbox:
    - [x] tomorrow I'll make another one
- [ ] etc...

**Comment by VivienZhou** [comment]
I have modified the content into checkboxes

**Comment by jhauswald** [comment]
Hey I just remembered I wanted to ask you: why isn't the final result printed to the test client? Its printed after the NLPService runs but it should be returned all the way through. Just making sure that's still happening.

**Comment by jhauswald** [comment]
this look done, closing
