### ISSUE TITLE
Sentiment Analysis

### ISSUE THREAD

**Issue by Thomas-Yang** [clarityinc/clarityeco#7]
Adding a sentiment analysis service into the ecosystem that processes the natural language to evaluate the emotion behind the sentences. Features includes the following:
   1. qualitatively evaluate the polarity of the natural language sentences;
     + positive or negative
   2. quantitatively score the polarity of the natural language sentences;
   3. leverage the power of both NLTK and Senna tools;
   4. wrap up as thrift service interacting with the ecosystem through command center;

**Comment by jhauswald** [comment]
closed by #16

**Comment by Thomas-Yang** [comment]
The comment out of the thrift library path is not included in the clarityinc/clarityeco repo(it is already in my forked repo). Do I need to submit a pull request again? Or you can directly pull from upstream?

**Comment by jhauswald** [comment]
You should just merge it directly into the dev branch, no need to submit a PR. or if you are working on more components for sentimental analysis open a new issue and add it to the command center milestone (the next release). How does SA hook to the cc?

**Comment by Thomas-Yang** [comment]
It is already merged into my dev branch. However, it is not appeared in the upstream repo. What did I miss?

**Comment by jhauswald** [comment]
You need to merge your dev branch with the upstream branch. Sort of like the merge --no-ff we were discussing. Or you can just submit a PR :)

**Comment by Thomas-Yang** [comment]
Cool. It is merged. I forgot to specify the upstream keyword.
